### ISSUE TITLE
Sections Classnames Geven  

### ISSUE THREAD

**Issue by Jason2426** [lisavanmansom/user-experience#8]
Ik zie dat je sections gebruikt wat al goed is maar geef voor de zekerheid classnames met betrekking tot de content die er in staat, om verwarring te voorkomen. en voor de herbruikbaarheid

**Comment by lisavanmansom** [comment]
Yes thanks! ik heb het aangepast.

[commit](https://github.com/lisavanmansom/user-experience/commit/0a54c39aa8ffbd790b00fcf5fffb9a4c036103f5)
